language: perl

jobs:
  include:
    - name: focal-arm64-graviton2
      dist: focal
      arch: arm64-graviton2
      os: linux
      group: edge
      virt: lxd
      perl: "5.30"
    - name: focal-amd64
      dist: focal
      arch: amd64
      os: linux
      perl: "5.30"
    - name: focal-arm64-graviton2
      dist: focal
      arch: arm64-graviton2
      os: linux
      group: edge
      virt: lxd
      perl: "5.29"
    - name: focal-amd64
      dist: focal
      arch: amd64
      os: linux
      perl: "5.29"
      
script:
  - return 0
